Repository zaphosting/docs, pull requests merged in 2020-04, with the labels that each got.

#100 replace imgur links
  de/account_contractsandprepaid.md
  de/account_vouchers.md
  de/docs_intern.md
  de/domain_easydns.md
  de/domain_profidns.md
  de/firststeps_register.md
  de/firststeps_rent_contractorprepaid.md
  de/fivem_dashboard.md
  de/gameserver_ftpaccess.md
  de/minecraft_addop.md
  de/minecraft_pluginuploader.md
  de/source_metamod_addadmins.md
  de/source_metamod_installation.md
  de/vserver_linux_docker.md
  de/vserver_windows_userdp.md
  de/webspace_dashboard.md
  en/beispiel.md
  en/docs_intern.md
  en/minecraft_pluginuploader.md
  en/vserver_linux_docker.md
  en/vserver_windows_userdp.md
  en/webspace_dashboard.md
  en/webspace_plesk_ftp.md
Labels: WIP

#128 fivem rcon
  de/fivem_rcon.md
  en/fivem_rcon.md
  sidebars.json
Labels: Done

#163 Raz partner guide DE&EN
  de/partner-guide.md
  en/partner-guide.md
  sidebars.json
Labels: help wanted

#153 Linux vServer Erstzugriff (SSH)
  de/vserver_linux_ssh.md
  en/vserver_linux_ssh.md
  sidebars.json
Labels: Done

#166 Gameserver/ts3update(einfügen der Spiele, die installiert werden können)
  de/vserver_linux_gs_interface.md
Labels: Done

#178 Domain stuff added
  de/domain_gameserver_srv_link.md
  de/domain_general_domain_info.md
  de/domain_order.md
  en/domain_gameserver_srv_link.md
  en/domain_general_domain_info.md
  en/domain_order.md
  sidebars.json
Labels: Done

#184 Vserver/rootserver kein internet windows
  de/vserver_windows_nointernet.md
  en/vserver_windows_nointernet.md
  sidebars.json
Labels: Done

#185 phpMyAdmin install
  de/vserver_linux_phpmyadmin.md
  en/vserver_linux_phpmyadmin.md
  sidebars.json
Labels: Done

#177 Raz create use license
  de/legal_use_brand_assets.md
  en/legal_use_brand_assets.md
  sidebars.json
  sprachvariablen/de.json
Labels: help wanted

#194 Assetto Corsa Guides
  de/assettocorsa_configure.md
  de/assettocorsa_mods.md
  en/assettocorsa_configure.md
  en/assettocorsa_mods.md
  sidebars.json
Labels: Done

#190 Create domain_records.md
  de/domain_records.md
  en/domain_records.md
  sidebars.json
Labels: Done

#193 Created vserver_windows_port.md DE
  de/vserver_windows_port.md
  en/vserver_windows_port.md
  sidebars.json
Labels: Done

#196 Musikbotverbinden Anleitung
  de/voiceserver_voicebot_connection.md
  en/voiceserver_voicebot_connection.md
  sidebars.json
Labels: Done

#206 add disable inventory guide & change money icon guide
  de/fivem_esx_changemoneyicon.md
  de/fivem_esx_disableinventory.md
  en/fivem_esx_changemoneyicon.md
  en/fivem_esx_disableinventory.md
  sidebars.json
  sprachvariablen/de.json
  sprachvariablen/en.json
Labels: Done

#205 some translations
  en/account_termination_and_cancellation_period.md
  en/assettocorsa_configure.md
  en/assettocorsa_mods.md
  en/fivem_mods_installaddon.md
  en/vserver_linux_gs_interface.md
Labels: Done

#217 Create spaceengineers_beomeadmin.md
  de/spaceengineers_becomeadmin.md
  en/spaceengineers_becomeadmin.md
  sidebars.json
Labels: Done

#224 Created domain_expertdns
  de/domain_expertdns.md
  en/domain_expertdns.md
Labels: Done

#225 Fb addiplinux
  de/vserver_linux_add_ip.md
  en/vserver_linux_add_ip.md
  sidebars.json
Labels: Done

#98 Passwort Änderung VPS/Root
  de/vserver_linux_ftp.md
  de/vserver_linux_password_change.md
  en/vserver_linux_ftp.md
  en/vserver_linux_password_change.md
  sidebars.json
Labels: Done
